# Generated by Django 4.2.3 on 2023-09-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_post_vto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vto',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
